# Generated by Django 4.2.6 on 2023-10-20 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=999)),
                ('servico', models.CharField(max_length=255)),
                ('local', models.CharField(max_length=255)),
                ('idade', models.DecimalField(decimal_places=0, max_digits=3)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uploader.image')),
            ],
        ),
    ]
