# Generated by Django 4.2.6 on 2023-10-16 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('backWH', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='descricao',
        ),
        migrations.AddField(
            model_name='people',
            name='capa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
        migrations.AddField(
            model_name='people',
            name='isbn',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='titulo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
