# Generated by Django 4.2.6 on 2023-10-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backWH', '0002_remove_people_descricao_people_capa_people_isbn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='titulo',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='capa',
            new_name='foto',
        ),
        migrations.RemoveField(
            model_name='people',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='people',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='people',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='people',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='servico',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
