# Generated by Django 4.2.6 on 2023-10-19 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('backWH', '0003_rename_titulo_people_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='foto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
    ]
