# Generated by Django 4.2.6 on 2023-10-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backWH', '0004_alter_people_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='local',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
