# Generated by Django 4.2.6 on 2023-10-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backWH', '0005_people_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='age',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
