# Generated by Django 4.2.6 on 2023-10-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backWH', '0006_people_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='age',
            new_name='idade',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='name',
            new_name='nome',
        ),
    ]
