# Generated by Django 4.2.6 on 2023-10-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backWH', '0007_rename_age_people_idade_rename_name_people_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='descricao',
            field=models.CharField(max_length=999),
        ),
    ]
