# Generated by Django 4.2.6 on 2023-10-20 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('backWH', '0008_alter_people_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='foto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uploader.image'),
        ),
    ]
